### ISSUE TITLE
Async test helpers waiting forever

### ISSUE THREAD

**Issue by simonihmig** [sir-dunxalot/ember-flash-messages#10]
I have encountered a strange issue, that took me a couple of hours to fix.

After integrating flash-messages, my existing acceptance test (where a flash message was generated) was stoping execution at some point. I could see in the ember inspector that a promise of the click test helper was pending infinitely, thus halting test execution.

I debugged my self through the ember internals, and found that in the Backburner class (Ember.run), the _timers array had some setTimeout timers that the test helper was waiting to be executed, but they would never execute because the timeout period was NaN. The function waiting for execution by these invalid timers was this one:
https://github.com/sir-dunxalot/ember-flash-messages/blob/master/addon/components/flash-message.js#L111-L115

So apparently in the Ember.run.later call the animationDuration was evaluated to NaN at some point, leading to those "corrupt" timer entries.

I have not tracked this down further. As I have already used a custom inherited flash-message component, I just overrode the animationDuration property to some static value, and from then on the test were completing successfully again.

Hope this helps to track this bug down!

**Comment by sir-dunxalot** [comment]
Thanks for the detailed issue! I really appreciate the research and time.

This is definitely a pressing issue as this addon should not be interfering with test suite speed. Are you able to show me the code for the particular test you caught this issue in? If not, is it an integration or unit test and what kind of ember-qunit helpers are you using (e.g. `moduleFor`, `moduleForComponent`)? Also, do you have an idea of how I could replicate the slow test speed in a test suite of my own?

Personally, I'm not a big fan of how the `animationDuration` is bound between components so that might be the bigger issue. The binding is brittle and not context aware - this issue highlights that.

Again, I really appreciate the help!

**Comment by simonihmig** [comment]
You're welcome! :)

Maybe you missed one important point: it is not about slow speed, it is really about infinitely waiting! The test suite would never complete, never ever! :)

It is an acceptance (integration) test, using `module`, the usuals setup generated by `ember g acceptance-test ...`. I could show you the test, but it is nothing special, very application specific stuff. I am using the `click` helper, but any other async helper would have the same issue as well I think, as they all wait for all promises to fulfill and all run loop timers to finish.

A test case would be: 
1. create a flash message
2. call an async test helper like `click`
3. call `andThen(function(){ok(true)});`

Im my case the `ok` assertions would have never been called, as the `click` helper would wait infinitely.
I do not know if that would be easily reproducable, or if there is some kind of edge case here...

If you are not able to reproduce this, I could try to help, but don't hold your breath, I don't know how soon time would permit this...

**Comment by sir-dunxalot** [comment]
Ok, got it. I'll be able to look into it this week. Just to clarify: you were clicking on the flash message component with the async helper, correct?

**Comment by simonihmig** [comment]
No, I was not. The click had nothing to do with the message!

**Comment by sir-dunxalot** [comment]
Ok, interesting. Thanks for following up - I'll try and get a fix up within the next four days.

**Comment by sir-dunxalot** [comment]
Sorry for the delay - had other issues come up and then this slipped past the radar. I'm planning on getting a fix up by the end of the weekend.

**Comment by sir-dunxalot** [comment]
@simonihmig This should have been fixed with #13. I'm going to be updating this addon to use a service within the next two weeks so that will be the long-term solution. Let me know fi you still encounter any issues and thanks for your patience!
