### ISSUE TITLE
Override flash-message template

### ISSUE THREAD

**Issue by melodyma** [sir-dunxalot/ember-flash-messages#20]
Hello,

I've extended your component as per your docs and I'm trying to override your flash-message.hbs, but encountering an issue.

In your docs here https://github.com/sir-dunxalot/ember-flash-messages/wiki/Flash-Message-Component#template , it says `You can easily change the flash message's template by overwriting my-app-name/templates/components/flash-message.hbs:`, but it doesn't work and still pulls the original template from the addon. Also, I don't want to overwrite your original template directly.

Thanks!

**Comment by sir-dunxalot** [comment]
Hi Melody,

I recently encountered this issue myself. It seems that the component's `layout` is now imported as a module too. So in the flash message component, we have something like:

```js
/* ember-flash-messages/components/flash-message.js */

import Ember from 'ember';
import layout from 'ember-flash-messages/templates/components/flash-message';

export default Ember.Component.extend({
  /* ... other properties... */
  layout: layout,
});
```

[You can see that code here](https://github.com/sir-dunxalot/ember-flash-messages/blob/master/addon/components/flash-message.js#L47).

What this means is, to overwrite the layout, you must import the layout from your app's tree:

```js
/* app-name/components/flash-message.js */

import FlashMessageComponent from 'ember-flash-messages/components/flash-message';
import layout from 'app-name/templates/components/flash-message';

export default FlashMessageComponent.extend({
  /* ... other properties... */
  layout: layout,
});
```

Does that make sense? This also has the benefit of keeping the original layout in the tree.

So the documentation here is out of date. I will mark this as a bug and will fix accordingly soon,
