### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by timini** [sir-dunxalot/ember-flash-messages#7]
I try to install into an ember cli project but then the project does not compile correctly:

```
Uncaught Error: Could not find module collections/shim
vendor.js:65 Uncaught Error: Could not find module ember-flash-messages/initializers/ember-flash-messages
```

**Comment by timini** [comment]
I think one of your deps has changed 

https://github.com/ember-cli/ember-cli-shims

**Comment by sir-dunxalot** [comment]
Thanks for the heads up. It looks like that's a result of the new Ember CLI org being created on Github. I'm about to push v1.5.0 so I'll update the Ember CLI version to 1.5.0 before I push. PR will be up soon.

**Comment by timini** [comment]
Great thanks looking forward to it :+1:

**Comment by sir-dunxalot** [comment]
Did you see my message above? Haha. I'm not sure the 0.5.0 update will fix this.

**Comment by timini** [comment]
looks like I have ember-cli version: 0.1.2

I will upgrade

**Comment by sir-dunxalot** [comment]
Ok, sounds good. Let me know if you're still having issues after that.

**Comment by timini** [comment]
I must be installing wrong I still get an error when I install this:
 ```Uncaught Error: Could not find module ember-flash-messages/initializers/ember-flash-messages```

this is what I have installed:

```
 DEBUG: -------------------------------
ember.js:15373 DEBUG: Ember                       : 1.8.1
ember.js:15373 DEBUG: Ember Data                  : 1.0.0-beta.12
ember.js:15373 DEBUG: Handlebars                  : 1.3.0
ember.js:15373 DEBUG: jQuery                      : 1.11.2
ember.js:15373 DEBUG: Ember Simple Auth           : 0.7.2
ember.js:15373 DEBUG: Ember Simple Auth OAuth 2.0 : 0.7.2
ember.js:15373 DEBUG: Ember Simple Auth Torii     : 0.7.2
ember.js:15373 DEBUG: -------------------------------
```

```
   ember --version
version: 0.1.5
Could not find watchman, falling back to NodeWatcher for file system events
node: 0.10.33
npm: 2.1.8
```

I am Installing just with one line:

```npm install --save-dev ember-flash-messages``

**Comment by sir-dunxalot** [comment]
I presume that error is coming from `app/initializers/ember-flash-messages.js`. I'm not sure what's going on here but I'll try and dig into it again. Sorry for the issues.

If you look in your `app.js` file do you see any of the other ember-flash-messages modules?

**Comment by sir-dunxalot** [comment]
I installed this into another Ember CLI app without fail.

I think the issue might be related to your app's NPM stuff. If you haven't figured out what's causing this issue, I'd try removing your `node_modules` and `tmp` folders, running `npm cache clean` and then `npm install --save ember-flash-messages`. Then run `npm install` (or `ember install`) and you should get a fresh install of all your NPM modules.

**Comment by timini** [comment]
Thanks for the help with this. I finally found the problem, it is a conflict with https://github.com/mysterlune/ember-cli-list-view

I have uninstalled that and now flash messages are working fine! thanks!

**Comment by sir-dunxalot** [comment]
Hey, thanks for following up! Good job finding the conflict - I'll open a new issue to fix the conflict.
